version: '3'
services:
    web:
        container_name: laravel-app-web
        image: nginx:1.15.6
        ports:
            - '8000:80'
        depends_on: # 追加
            - app
        volumes:
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    app:
        container_name: laravel-app-app
        build: ./docker/php
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
    mysql:
        container_name: laravel-app-db
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel-db
            MYSQL_USER: rsugaya
            MYSQL_PASSWORD: rsugaya
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data:
